# Site settings
title: Cheng Wu
email: chengwu@uchicago.com
description: Cheng Wu’s personal website

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/pub/cheng-wu/
  - title: weibo
    url: http://www.weibo.com/chenglouis
  - title: facebook
    url: https://www.facebook.com/Louis.wucheng
  - title: bitbucket 
    url: https://bitbucket.org/cheng-wu
  - title: github
    url: https://github.com/cheng-wu

# Postal address (add as many lines as necessary)
address:
  - line: 6117 S. Ellis Ave, Apt 3S
  - line: Chicago, IL 60637

# Build settings
markdown: kramdown
permalink: pretty
